// Frases por faixa de horário (spec seção 5/6/31) — sempre no fuso de São
// Paulo, ver time.ts. Cada faixa tem seu próprio tom: madrugada é mais
// "cuidado com você mesmo", manhã é mais motivacional-irônica, fim de
// expediente brinca com o embate "hora de ir embora vs. terminar logo".
import { bank } from "./bank-helper";
import type { FlowMessage } from "./types";

export const lateNight: FlowMessage[] = bank("lateNight", [
  "Bom dia ou boa noite? Neste ponto já perdemos o controle.",
  "02:17 no relógio. Talvez esse corte possa esperar até amanhã.",
  "Você ainda está aqui? O Premiere agradece, sua cama não.",
  "Você abriu o G2 FLOW depois da meia-noite. Temos perguntas, mas deixa pra depois.",
  "Novo dia detectado. O anterior chegou a terminar de verdade?",
  "Madrugada. Hora oficial de jurar 'só mais um ajuste' e sair daqui só às 3h.",
  "A essa hora só existem duas espécies: quem dorme e quem exporta.",
  "Ctrl+S antes de qualquer decisão criativa tomada depois da meia-noite.",
  "Se o take parece ótimo agora, reveja de manhã. A madrugada mente.",
  "Silêncio total no escritório. Só o fã do computador rendendo.",
  "A que horas mesmo você disse que ia parar? Foi há duas horas.",
  "Madrugada produtiva ou insônia disfarçada de produtividade? Só você sabe.",
  "Essa exportação vai rodar sozinha. Você pode ir dormir. Pode mesmo.",
  "Os prazos de amanhã agradecem, mas seu sono também merece uma chance.",
  "A cidade dorme. O render, não.",
  "Última decisão de cor tomada às 3 da manhã raramente sobrevive à luz do dia.",
  "Se alguém perguntar 'por que ainda tá acordado', a resposta é sempre 'só mais um render'.",
  "Nesse horário o café já não é bebida, é procedimento.",
  "Você e o cursor piscando são as únicas coisas ainda em movimento agora.",
  "A madrugada tem um jeito único de fazer qualquer prazo parecer urgente.",
]);

export const early: FlowMessage[] = bank("early", [
  "Bom dia. Quem marca diária às 6h claramente não gosta de dormir.",
  "Bom dia. A diária começa às 8h. A sua existência começou bem antes.",
  "Bom dia. Café primeiro, decisões criativas depois.",
  "Cedo assim só quem tem captação ou insônia.",
  "O sol ainda está decidindo se aparece. Você já está de pé.",
  "Bom dia. Hoje o despertador venceu antes do prazo.",
  "Ainda é cedo, mas o prazo já está de olho aberto.",
  "Bom dia. Bateria carregada, café servido, expectativas administráveis.",
  "Acordar cedo pra editar é dedicação. Acordar cedo pra revisar é otimismo.",
  "O escritório ainda está vazio. Aproveite esse silêncio, ele tem prazo de validade.",
  "Bom dia. O trânsito ainda não decidiu ser um problema.",
  "Cedo demais pra reunião, cedo demais pra decisão de cor, na hora certa pro café.",
  "Bom dia. Hoje começou antes de qualquer notificação do cliente.",
  "A cidade ainda acorda. Você já está na timeline.",
  "Bom dia. Ninguém te elogiou por chegar cedo ainda, mas o dia é longo.",
  "Manhã fria, café quente, prazo do mesmo jeito de sempre.",
  "Bom dia. Hoje o silêncio da manhã ainda não virou grupo de cliente no WhatsApp.",
  "Cedo o suficiente pra planejar o dia. Tarde o bastante pra já ter pauta.",
]);

export const morning: FlowMessage[] = bank("morning", [
  "Bom dia. Seu prazo já acordou antes de você.",
  "Bom dia. Ctrl+S e fé.",
  "Bom dia. Bora transformar café em conteúdo.",
  "Bom dia. O dia começou, o backlog também.",
  "Manhã produtiva começa com a timeline aberta e o e-mail fechado.",
  "Bom dia. A caixa de entrada já tem pelo menos um 'só um ajustezinho'.",
  "Bom dia. Hoje é dia de decidir corte antes que alguém decida por você.",
  "A manhã é sua. A tarde já tem dono: o cliente.",
  "Bom dia. Primeiro café, depois o mundo. Ou pelo menos o Premiere.",
  "Bom dia. Que a proxy carregue rápido e o briefing seja claro.",
  "Manhã nova, mesma timeline de ontem esperando por você.",
  "Bom dia. A produtividade da manhã dura até a primeira reunião.",
  "Bom dia. Hoje o café rende mais que o render.",
  "Já são 9h e o backlog já sabe seu nome.",
  "Bom dia. O dia inteiro pela frente. Pelo menos até o almoço.",
  "Manhã é pra planejar o dia. Tarde é pra sobreviver a ele.",
  "Bom dia. Hoje sem novidade: prazo apertado, café forte.",
  "Bom dia. A timeline não julga quem chega sem café. Mas deveria.",
  "Bom dia. Que o autosave esteja sempre com você.",
  "Manhã começando bem: internet estável e sem chamada às 8h.",
  "Bom dia. O dia só oficialmente começa depois do primeiro Ctrl+S.",
  "Bom dia. Hoje a lista de tarefas parece pequena. Aproveite essa ilusão.",
  "Café na mão, projeto aberto, expectativas moderadas.",
  "Bom dia. A criatividade só aparece depois da segunda xícara. Ciência.",
  "Bom dia. Comece pela tarefa mais difícil. Ou pela mais fácil. Só comece.",
  "Manhã tranquila até o primeiro áudio de cliente de 4 minutos.",
  "Bom dia. Que hoje o Frame.io carregue os comentários sem travar.",
  "Bom dia. A criatividade chegou, junto com uma notificação do cliente.",
  "Bom dia. O dia começa sempre otimista. Fica de olho na tarde.",
  "Bom dia. Hoje o café é o verdadeiro protagonista da produção.",
  "Bom dia. A timeline te espera exatamente onde você deixou ontem.",
  "Bom dia. Que o wifi do escritório aguente o upload de hoje.",
  "Manhã de segunda ou não, o backlog não tira folga.",
  "Bom dia. Um dia de cada vez. Ou um render de cada vez, no mínimo.",
  "Bom dia. Hoje promete. Amanhã a gente vê se cumpriu.",
]);

export const lunch: FlowMessage[] = bank("lunch", [
  "Boa tarde. Você almoçou ou está sobrevivendo de café?",
  "Boa tarde. Pausa técnica para fingir equilíbrio entre vida e trabalho.",
  "Meio-dia. Hora oficial de fechar a timeline e abrir o cardápio.",
  "Boa tarde. O prazo pode esperar 40 minutos. Coma direito.",
  "Almoço: a única reunião do dia que ninguém cancela.",
  "Boa tarde. Comer na frente do computador não conta como pausa de verdade.",
  "Meio-dia bateu. O prazo também, mas finge que não viu.",
  "Boa tarde. Metade do dia foi. A outra metade agradece se você almoçar direito.",
  "Boa tarde. Hora de trocar café por comida de verdade. Pelo menos uma vez.",
  "Boa tarde. Timeline pausada, fome ativada.",
  "Boa tarde. Se puder, coma longe da tela. Se não puder, tudo bem, a gente entende.",
  "Meio-dia. A produtividade da manhã foi arquivada. A da tarde ainda não chegou.",
  "Boa tarde. Ninguém edita bem de estômago vazio.",
  "Boa tarde. O prazo sobrevive sem você por uma hora. Vai.",
  "Boa tarde. Pausa pro almoço: o único prazo que você sempre cumpre.",
  "Boa tarde. Comer é produtivo. Ninguém te falou isso antes?",
  "Boa tarde. A timeline vai estar exatamente onde você deixou. Ela sempre está.",
  "Meio-dia bateu, a fome também. O render que espere.",
  "Boa tarde. Hora do almoço: onde toda decisão de corte é adiada com prazer.",
  "Boa tarde. Nem toda pausa precisa de justificativa. Essa, principalmente.",
]);

export const afternoon: FlowMessage[] = bank("afternoon", [
  "Boa tarde. Metade do dia passou e o prazo percebeu.",
  "Boa tarde. Se começar agora, tecnicamente você começou hoje.",
  "Boa tarde. A tarde é onde os planos da manhã vão pra morrer.",
  "Boa tarde. Hora de decidir se hoje ainda dá tempo ou se já virou amanhã cedo.",
  "Boa tarde. O café da tarde é diferente. Mais desesperado.",
  "Boa tarde. A timeline está exatamente onde você deixou de manhã. Ela não se move sozinha.",
  "Boa tarde. Ainda dá tempo. Talvez. Depende do render.",
  "Boa tarde. A produtividade pós-almoço é um mito que ninguém provou.",
  "Boa tarde. Hora de fingir que o dia ainda está sob controle.",
  "Boa tarde. Metade do café já foi. A metade da produtividade, também.",
  "Boa tarde. A tarde separa quem planeja de quem executa.",
  "Boa tarde. Ainda dá tempo de virar o jogo. Ou pelo menos empatar.",
  "Boa tarde. O sol começa a se despedir, o prazo não.",
  "Boa tarde. Se o dia foi corrido até agora, calma: ainda tem mais um pouco pela frente.",
  "Boa tarde. Hora de decidir: sprint final ou aceitar que amanhã existe.",
  "Boa tarde. A concentração da tarde é mais rara que aprovação sem alteração.",
  "Boa tarde. Falta pouco pro fim do expediente. Falta muito pro fim da lista.",
  "Boa tarde. Um café a mais nunca fez mal a ninguém. Bom, quase ninguém.",
  "Boa tarde. A tarde sempre parece mais curta que a manhã. Estatística ou o prazo mexendo com sua cabeça.",
  "Boa tarde. Hora de revisar o que foi feito de manhã. Spoiler: menos do que parecia.",
  "Boa tarde. Ainda dá pra fechar um corte antes do fim do dia. Talvez.",
  "Boa tarde. A cafeína da manhã já foi. A da tarde é obrigatória.",
  "Boa tarde. O dia ainda tem capítulos. Alguns bons, outros nem tanto.",
  "Boa tarde. Falta pouco pra descobrir se hoje foi produtivo ou só cansativo.",
  "Boa tarde. A luz do fim da tarde é ótima pra tudo, menos pra terminar a lista de hoje.",
  "Boa tarde. Segunda metade do dia: onde as boas intenções da manhã são testadas.",
  "Boa tarde. Hora de decidir entre revisar de novo ou simplesmente entregar.",
  "Boa tarde. O prazo de hoje está observando o relógio junto com você.",
  "Boa tarde. Reta final do expediente se aproximando. A lista, nem tanto.",
  "Boa tarde. A tarde é sempre mais rápida quando tem prazo no fim dela.",
]);

export const eveningWrap: FlowMessage[] = bank("eveningWrap", [
  "Boa noite. O expediente acabou. O render, não.",
  "18h chegou. O planner não vai julgar se você fechar tudo agora.",
  "Boa noite. Hora de decidir entre 'termino rapidinho' e 'amanhã eu vejo'.",
  "18h bateu e a timeline finge que não percebeu.",
  "Boa noite. O dia oficial acabou. O extraoficial, quem sabe.",
  "18h. O horário em que 'só mais 10 minutos' vira uma hora.",
  "Boa noite. Se já entregou, vá embora. Se não, calma, ainda dá.",
  "O expediente pediu pra sair. Algumas tarefas ainda não deixaram.",
  "Boa noite. A produtividade dessa hora é sempre uma surpresa, boa ou ruim.",
  "18h e o WhatsApp ainda não avisou que o dia acabou pro cliente também.",
  "Boa noite. Fechar tudo agora ou virar 'trabalho de casa'? Você decide.",
  "O sol se pôs. Algumas timelines, não.",
  "Boa noite. Se sobrou pouco pra terminar, capricha. Se sobrou muito, respira.",
  "18h chegou trazendo a pergunta de sempre: dá tempo ou não dá?",
  "Boa noite. O expediente é uma sugestão, o cansaço é fato.",
  "Fim de tarde. Metade decide ir embora, metade decide 'só mais um pouco'.",
  "Boa noite. A cidade acende as luzes. Algumas timelines também continuam acesas.",
  "18h. Quem entregou hoje já foi. Quem não entregou está lendo isso.",
  "Boa noite. O dia rendeu o que rendeu. Amanhã tem mais.",
  "Fim do expediente oficial. Início do expediente que ninguém admite fazer.",
  "Boa noite. Se a timeline ainda está aberta, pelo menos feche as abas que não precisa.",
  "18h e a única certeza é que o café já perdeu a força.",
  "Boa noite. Hora de escolher entre revisar mais uma vez ou confiar no trabalho feito.",
  "Boa noite. O expediente encerrou. As notificações do cliente, nunca.",
]);

export const night: FlowMessage[] = bank("night", [
  "Boa noite. Seu cérebro entrou em modo proxy.",
  "Boa noite. Último Ctrl+S do dia. Em teoria.",
  "22h30. Talvez aquele corte não precise ser perfeito hoje.",
  "Boa noite. Se ainda está na timeline, pelo menos coloca uma música boa.",
  "Boa noite. A essa hora, qualquer decisão de cor merece uma segunda olhada amanhã.",
  "Boa noite. O dia oficialmente já era. Isso aqui já é hora extra emocional.",
  "Boa noite. Quem ainda está trabalhando merece um café melhor do que esse frio na mesa.",
  "Já são quase 22h e a timeline ainda está com a luz acesa.",
  "Boa noite. Amanhã esse mesmo corte vai parecer óbvio. Hoje ele só parece impossível.",
  "Boa noite. A noite deixa tudo mais dramático, inclusive o prazo.",
  "Boa noite. Se o objetivo era só 'dar uma olhadinha', já passou faz tempo.",
  "23h. A hora em que qualquer prazo parece pessoal.",
  "Boa noite. O silêncio da noite é ótimo pra focar e péssimo pra parar.",
  "Boa noite. Quem trabalha essa hora sabe que amanhã cedo vai cobrar a conta.",
  "Boa noite. Última exportação do dia, prometo (não prometo).",
  "Boa noite. O Premiere não dorme, mas você deveria pensar nisso.",
  "Boa noite. A criatividade dessa hora é ousada. Reveja com calma amanhã.",
  "Boa noite. Se está aqui às 22h por escolha, respeito. Se for por prazo, força.",
  "Boa noite. A cidade desacelera. A timeline, só se você fechar o programa.",
  "Boa noite. Quase meia-noite e o cursor ainda pisca esperando decisão.",
  "Boa noite. Trabalhar de madrugada rende a mesma coisa que trabalhar de dia, só que mais cansado.",
  "Boa noite. Se decidiu parar agora, ótima decisão. Se decidiu continuar, café.",
  "Boa noite. A noite é jovem. Seus olhos, nem tanto, depois de 10h de tela.",
  "Boa noite. Fechando o dia ou só fechando os olhos por um segundo entre um render e outro?",
]);
